replicaCount: 1

image:
  repository: octoprint/octoprint
  tag: latest

service:
  port: 5000

hostname: octopi.kserver
hostPath:
  data: /home/kzorluoglu/charts/octoprint/data/
  config: /home/kzorluoglu/charts/octoprint/config.yaml

persistence:
  enabled: true
  existingClaim: "" # If you have an existing PVC, provide the name here
  storageClassName: "standard" # StorageClass to use for PVC provisioning
  accessMode: "ReadWriteOnce"
  size: "5Gi"

